### ISSUE TITLE
Link to pre-generated pseudo label data

### ISSUE THREAD

**Issue by sparshgarg23** [wkfdb/MarvelOVD#2]
Hi it seems that the link to pre-generated pseudo label data is not working.Can you reupload it.
thanks for open sourcing your implementation.

**Comment by wkfdb** [comment]
I see the outdated link. I'll upload a new link within 24 hours.

**Comment by sparshgarg23** [comment]
thanks the weight file for generating the pseudo labels is also outdated.
if I have any more questions,would it be okay to get in touch?

**Comment by wkfdb** [comment]
the VL-PLM pseudo-label data, rpn weight for pseudo label generation and our generated candidate pseudo-label data are updated. You can also get in touch with my email (the first author of the paper).

**Comment by sparshgarg23** [comment]
thanks for uploading the files.Quick question,when we download coco,it already has instance_val and instance_train.json in it,and I saw the  uploaded files share the same name,so should these be placed in the open_voc folder?

**Comment by wkfdb** [comment]
They are different and it's not necessary to replace, cause they are in different folders. You should download the shared file and put them into open_voc folder. This step is none of business with the original json file.
